/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AboutMe': RouteRecordInfo<'/AboutMe', '/AboutMe', Record<never, never>, Record<never, never>>,
    '/ContactMe': RouteRecordInfo<'/ContactMe', '/ContactMe', Record<never, never>, Record<never, never>>,
    '/GalleryPage': RouteRecordInfo<'/GalleryPage', '/GalleryPage', Record<never, never>, Record<never, never>>,
    '/LogIn': RouteRecordInfo<'/LogIn', '/LogIn', Record<never, never>, Record<never, never>>,
    '/ProfilePage': RouteRecordInfo<'/ProfilePage', '/ProfilePage', Record<never, never>, Record<never, never>>,
    '/ReportAnIssue': RouteRecordInfo<'/ReportAnIssue', '/ReportAnIssue', Record<never, never>, Record<never, never>>,
    '/ReviewPage': RouteRecordInfo<'/ReviewPage', '/ReviewPage', Record<never, never>, Record<never, never>>,
    '/ShopCart': RouteRecordInfo<'/ShopCart', '/ShopCart', Record<never, never>, Record<never, never>>,
    '/SignUp': RouteRecordInfo<'/SignUp', '/SignUp', Record<never, never>, Record<never, never>>,
  }
}
