###
GET http://localhost:3000/api/v1/reviews/15


###
PATCH http://localhost:3000/api/v1/reviews/1
Content-Type: application/json

{
    "userId": "1",
    "title": "Delicious",
    "text": "Moshe Plotkin would have loved this!",
    "rating": "5",
    "image": "https://res.cloudinary.com/dv8u0g7xm/image/upload/v1733869275/IMG_3883_xe22uo.png"
}