###
GET http://localhost:3000/api/v1/reviews/15


###
POST http://localhost:3000/api/v1/reviews
Content-Type: application/json

{
    "userId": "1",
    "title": "dawdawdawdawd",
    "text": "dawdawd",
    "rating": "5",
    "image": null
}